### ISSUE TITLE
求教

### ISSUE THREAD

**Issue by hljcode** [UncP/Mushroom#6]
你好，我想问一下我应该怎样跟着你的项目也来写一个数据库呢？希望能给些建议，我自身有c语言和数据结构的基础，希望能通过写数据库来练手，提高工程能力。

**Comment by UncP** [comment]
去知乎搜下"如何实现数据库"之类的问题

**Comment by hljcode** [comment]
我就是从知乎过来的，发现答主好厉害。答主我想做点东西出来，但非科班，只有之前的一些基础，现在在准备考计算机的研，但发现工程能力太弱了，能给些建议吗？

**Comment by hljcode** [comment]
我就是从知乎过来的，发现答主好厉害。答主我想做点东西出来，但非科班，只有之前的一些基础，现在在准备考计算机的研，但发现工程能力太弱了，能给些建议吗？

**Comment by hljcode** [comment]
你好，我是从知乎过来的，发现答主好厉害。我自身为非科班，基础一般，在准备计算机的研究生，但发现实战功底太弱。能给些建议吗？

**Comment by UncP** [comment]
直接在知乎上搜
