### ISSUE TITLE
compile error on branch V1.2.1 & V1.2.2

### ISSUE THREAD

**Issue by LinuxBars** [UncP/Mushroom#7]
hi, I am trying to compile your code in CentOS7 64bit，but i got this error on both two branch:

g++ -std=c++11 -Wall -Wextra -O3 -o distributed_index_test blink/page_pool.o blink/pool_manager.o blink/db.o blink/b_link_tree.o blink/page.o network/socket.o network/poller.o network/channel.o network/connection.o network/endpoint.o network/eventbase.o network/server.o network/buffer.o rpc/rpc_server.o rpc/rpc_connection.o raft/raft_server.o ../test/distributed_index.cpp -pthread
../test/distributed_index.cpp:12:34: fatal error: ../src/mushroom/db.hpp: No such file or directory
 #include "../src/mushroom/db.hpp"
                                  ^
compilation terminated.
make: *** [distributed_index_test] Error 1

appreciate for any help!

**Comment by UncP** [comment]
try v1.0.0

**Comment by LinuxBars** [comment]
sorry but the same error message occured.

**Comment by UncP** [comment]
close this due to lack of reply.
